# Generated by Django 3.0.6 on 2020-05-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oct', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oct_image',
            name='defect_type',
            field=models.CharField(choices=[('CNV', 'Choroidal neovascularization(CNV)'), ('DME', 'Diabetic macular edema (DME)'), ('DRN', 'Drusen'), ('NRM', 'Normal')], default='NRM', max_length=3),
        ),
    ]
