# Generated by Django 3.0.6 on 2020-12-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XRAY_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='xray_uploads/')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('defect_type', models.CharField(choices=[('PNM', 'Pleumonia'), ('NRM', 'Normal')], default='NRM', max_length=3)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
